### ISSUE TITLE
Flytt deltakerbrukere-profil-kort til UKMusers

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMwp_dashboard#10]
Denne er nok fortsatt gyldig.

Nå vil alle som er admin for ett eller flere områder måtte velge kommune/fylke i useradmin_menu.

De som ikke er admins derimot, må få en kontroll-panel-velger i sin user_admin

**Comment by mariusmandal** [comment]
Det er et par ting som må ivaretas når man laster opp bilder (sånn at systemet er optimalt allerede fra v1)
- [ ] Fulloppløselig utgave må være tilgjengelig
- [ ] Bildet bør (hvis mulig) gå gjennom opplastingsfunksjonen for UKMbilder (eller tilsvarende) slik at
 - [ ] a) bildet tagges med innslag (vi har jo p_id på brukeren)
 - [ ] b) fulloppløselig flyttes til private_sync og (gjennom funksjoner i UKMbilder) flyttes til dig.ark
 - [ ] c) registrert bilde i WP ikke blir full oppløsning, men en nedskalert utgave (gjennom funksjoner i UKMbilder)

- [ ] Ved visning bør optimalt sett bildet lenkes til det "fulloppløselige" (komprimert via UKMbilder) lenkes opp, slik at det er mulig å se bildet i stor størrelse etter arkivering av sesong (HTMLifisering av nettsiden)

**Comment by mariusmandal** [comment]
For å benytte UKMbilder-funksjonen tror jeg det enkleste er å trigge følgende to ajax-script:
##### 1. last opp og lagre
Laster opp bildet, lagrer det i bilder-tabellen, og returnerer en ID (ukm_bilder-tabellen)
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_uploaded_image.inc.php
##### 2. komprimering
Sørg for at bildet blir komprimert
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_compress.inc.php
##### 3. tagg bildet
Sett user_id = user_id av $current_user
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_do_tag.inc.php

**Comment by mariusmandal** [comment]
For å finne brukere som ikke har tilgang til områder, må det sjekkes både for fylke- og kommune (som vi har gjort ca her: 
https://github.com/UKMNorge/UKMnettverket/blob/master/UKMnettverket.php#L66
(current admin finner du her)
https://github.com/UKMNorge/UKMnettverket/blob/master/UKMnettverket.php#L46

**Comment by mariusmandal** [comment]
Denne gir en liste over hvilke blogger brukeren har tilgang til:
https://codex.wordpress.org/Function_Reference/get_blogs_of_user
