### ISSUE TITLE
Enklere måte å laste opp dokumenter på

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_dashboard#12]
Torstein savner enklere måte å laste opp styredokumenter på. Helt enig, dette bør på plass :)

**Comment by mariusmandal** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ThgoBN8Y&#x2F;183-enklere-opplasting-av-dokumenter"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Enklere opplasting av dokumenter</a>

**Comment by AsgeirSH** [comment]
Fixed by [UKMNorge/UKMdocs](https://github.com/UKMNorge/UKMdocs)
