### ISSUE TITLE
Info om testkommuner

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_dashboard#2]
Det bør være et eget menyvalg for hjelpefiler og dokumenter
Herunder bør det være tydelig info om hvordan man logger inn og melder seg på testkommunen

**Comment by AsgeirSH** [comment]
@mariusmandal Hva skal egentlig inn her? Info om testkommuner for hvem? Fylkeskontakter / lokalkontakter? Hvor? I dashboard? I så fall ikke melder seg på testkommunen via UKMdelta, men UKMdeltakere?

Og hva slags hjelpefiler og dokumenter bør inn et menyvalg med navn?

**Comment by mariusmandal** [comment]
Dette kan legges inn under "brukerstøtte" i arrangørsystemet
Opplys om hvilket brukernavn og passord som gjelder for fylket, og hvordan de går frem for å logge inn som "gjester"-brukeren.

http://ukm.no/wp-admin/admin.php?page=UKMwpd_support

Målet er at lokal- og fylkeskontakter kan logge inn som arrangøren "gjester" og sette opp en hel mønstring hvis ønskelig i forbindelse med en demo, eller at lokalkontakter kan logge inn og prøve seg frem i systemet.

OBS: Ettersom dette er en delt bruker må lokalkontaktene gjøres oppmerksom på at kollegaer kan være innlogget samtidig og gjøre andre endringer på kommunen.
