### ISSUE TITLE
Re-introduser kommune- og fylke-velgeren

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_dashboard#25]
List ut alle kommuner i en filter-liste.
Lenkene må peke til kommune/fylke-siden, samt til UKMnettverket, med valgt kommune / fylke

Tidligere listet vi ut mønstringer, nå trenger vi bare å hente kommuner + fylker.

Se 
https://github.com/UKMNorge/UKMwp_dashboard/blob/master/twig/network/support.html.twig
og 
https://github.com/UKMNorge/UKMwp_dashboard/blob/master/controller/network/support.controller.php

**Comment by christianhva** [comment]
Søk funksjonalitet funker men fylker/kommuner i lista mangler lenke til siden. Begynner på det nå 🤓
