### ISSUE TITLE
Melding til lokalkontakter om stimuleringsmidler

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMwp_dashboard#4]
2 uker før fristen til stimuleringsmidler går ut må det komme en gul melding "Snart frist for stimuleringsmidler", som 3 dager før fristen blir rød, og forsvinner tvert fristen er ute.

**Comment by mariusmandal** [comment]
15. januar
15. mai
15. oktober

**Comment by mariusmandal** [comment]
Legg til menyvalg "stimuleringsmidler" i network admin som sier: følgende frister varsles med gult 3 uker før og rødt 1 uke før fristen går ut:

Frister kan hardkodes i array

**Comment by AsgeirSH** [comment]
![skjermbilde 2016-02-15 kl 10 55 40](https://cloud.githubusercontent.com/assets/1831028/13045283/c758a6ec-d3d2-11e5-865e-5ba0f99e698e.png)
![skjermbilde 2016-02-15 kl 10 55 52](https://cloud.githubusercontent.com/assets/1831028/13045284/c769826e-d3d2-11e5-8a7d-84a66dcbd144.png)
